language: ruby

rvm:
  - 2.4.7
  - 2.5.6
  - 2.6.4
  - ruby-head

cache: bundler
bundler_args: --jobs=4 --retry=3
sudo: false


before_install: 'gem update --system'

script:
  - bundle exec rake

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
