Rake:
  Include:
    - 'Rakefile'
    - '**/*.rake'

Rake/ClassDefinitionInTask:
  Description: 'Do not define a class or module in rake task, because it will be defined to the top level.'
  Enabled: true
  VersionAdded: '0.3.0'

Rake/Desc:
  Description: 'Describe the task with `desc` method.'
  Enabled: true
  VersionAdded: '0.1.0'

Rake/MethodDefinitionInTask:
  Description: 'Do not define a method in rake task, because it will be defined to the top level.'
  Enabled: true
  VersionAdded: '0.2.0'
